[package]
name = "routbox"
version = "0.1.0"
edition = "2021"
authors = ["Daniele Guarascio <guarascio.daniele@gmail.com"]
readme = "README.md"
repository = "https://github.com/Guara92/routbox"
keywords = ["outbox", "database", "distributed-systems", "kafka", "async"]
categories = ["asynchronous"]
description = "A library to easily implement an outbox pattern"

[features]
pg_rust_async = ["tokio-postgres"]
pg_diesel_async = ["diesel-async", "diesel"]
kafka = []

[dependencies]
thiserror = "1"
serde = "1"
serde_json = "1"
uuid = { version = "1", features = ["v7"] }
tokio-postgres = { version = "0.7", optional = true, features = ["with-serde_json-1", "with-uuid-1"] }
diesel = { version = "2.2", optional = true, features = ["serde_json", "uuid"] }
diesel-async = { version = "0.5", optional = true, features = ["postgres"] }
