[package]
name = "routbox"
version = "0.1.0"
edition = "2024"
authors = ["Daniele Guarascio <guarascio.daniele@gmail.com"]
readme = "README.md"
repository = "https://github.com/Guara92/routbox"
keywords = ["outbox", "database", "distributed-systems", "kafka", "async"]
categories = ["asynchronous"]
description = "A library to easily implement an outbox pattern"

[features]
pg_rust_async = ["tokio-postgres"]
pg_diesel_async = ["diesel-async", "diesel"]
pg_diesel_blocking = ["diesel/postgres"]
kafka_relay = ["rdkafka"]

[dependencies]
thiserror = "2"
serde = "1"
serde_json = "1"
uuid = { version = "1", features = ["v7"] }
tokio-postgres = { version = "0.7", optional = true, features = ["with-serde_json-1", "with-uuid-1"] }
diesel = { version = "2.2", optional = true, features = ["serde_json", "uuid"] }
diesel-async = { git = "ssh://git@github.com/weiznich/diesel_async.git", rev = "c9730f6ddd7012d1d13e37262fc31d256e699aca", optional = true, features = ["postgres"] }
rdkafka = { version = "0.37", optional = true, features = ["tokio"] }

[dev-dependencies]
diesel = { version = "2.2", features = ["serde_json", "uuid"] }
dotenvy = "0.15"
tokio = { version = "1", features = ["macros"] }
serde = { version = "1", features = ["derive"] }
uuid = { version = "1", features = ["v7", "serde"] }
jiff = { version = "0.2", features = ["serde"] }
jiff-diesel = { version = "0.1", features = ["postgres"] }
